---
title: "206 HW 5"
author: "Joslyn Fritz"
date: "11/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r packages and files}

library(tidyverse)
library(tidyr)
library(vcdExtra)
library(car)
library(onewaytests)
library(gridExtra)
library(kableExtra)
library(effsize)
library(ggplot2)
library(ggsignif)
library(stargazer)

faculty_salary <- read_csv("Faculty salary data.csv")

doc_med_salary <- read_csv("Median salary for doctorals.csv")

grad_enroll <- read_csv("Grad enrollment.csv")

phd_fields <- read_csv("PhDs by Field.csv")

```



```{r}
## 1. compare trends in total graduate enrollment

total_grad_mvf <- ggplot(grad_enroll, aes(x = year)) + 
  geom_line(aes(y = male_total, color = "male_total"))+
  geom_line(aes(y = female_total, color = "female_total"))+
  xlab("Year") +
  ylab("Total Enrollment") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"), 
        text = element_text(family = "serif"))+
  theme(legend.text=element_text(size=15)) +
  theme(legend.title=element_blank()) 
  
  total_grad_mvf
  


```

```{r}
## Find the correlation coefficient for each line

# Perform linear regression

male_model <- lm(male_total ~ year, data = grad_enroll)
male_model
summary(male_model)

female_model <- lm(female_total ~ year, data = grad_enroll)
female_model
summary(female_model)

```

```{r}
# Model diagnostics 

plot(male_model)
plot(female_model)

```

```{r}
# Pearson's R

male_r <- cor.test(grad_enroll$male_total, grad_enroll$year)
male_r

female_r <- cor.test(grad_enroll$female_total, grad_enroll$year)
female_r
```
###2. Chi Squared shifts in Phd recipients by field of study
```{r}
phd_1985 <- read_csv("phd_1985.csv") %>% 
  select(Male, Female)  
  
rownames(phd_1985) <- c("Physical sciences and earth sciences", "Engineering", "Education", "Humanities and arts")

prop_1985 <- prop.table(as.matrix(phd_1985), 1)
prop_1985

chi_test <- chisq.test(phd_1985)
chi_test

```

